### ISSUE TITLE
Buscar Herramientas para elaborar pruebas

### ISSUE THREAD

**Issue by jazz1228** [calidadudea/CalidadTesting2019#1]
Consultar las herramientas más populares en el mercado actual que permitan hacer diferentes tipos de pruebas, en su preferencia, herramientas open source

**Comment by alejovillegas7** [comment]
[Herramientas para testing.pdf](https://github.com/calidadudea/CalidadTesting2019/files/3535470/Herramientas.para.testing.pdf)

**Comment by Basdf** [comment]
@DiegOliveros @natienamorado @veluaru @joh95 
- Posee descripción.
- Está asociada a un Milestone.
- Tiene un label.
- Está asociada a un proyecto.
- No tiene tareas asociadas.
- Tiene personas encargadas.
- Cuenta con documentación.

**Comment by alejovillegas7** [comment]
Consultar las herramientas más populares en el mercado actual que permitan hacer diferentes tipos de pruebas, en su preferencia, herramientas open source

- [x] Buscar herramientas de gestión de pruebas

- [x] Buscar herramientas para pruebas funcionales

- [x] Buscar herramientas para pruebas de carga y rendimiento

- [x] Buscar herramientas de gestión de pruebas(comerciales)

- [x] Buscar herramientas para pruebas funcionales(comerciales)

- [x] BUscar herramientas para pruebas de carga y rendimiento(comerciales)

- [x] Seleccionar mejores herramientas  mercado actual

**Comment by Basdf** [comment]
@DiegOliveros @natienamorado @veluaru @joh95
issue completo, lo pueden cerrar
