### ISSUE TITLE
Ejemplo y / o Guía de automatización de pruebas en Front

### ISSUE THREAD

**Issue by jazz1228** [calidadudea/CalidadTesting2019#10]
Se debe mostrar un ejemplo o guía sencilla donde se muestre el uso de la herramienta elegida en Front para la automatización de las pruebas

**Comment by jazz1228** [comment]
Se debe mostrar un ejemplo o guía sencilla donde se muestre el uso de la herramienta elegida en Front para la automatización de las pruebas

**Comment by jazz1228** [comment]
[PRUEBAS AUTOMATIZADAS EN ANGULAR.pdf](https://github.com/calidadudea/CalidadTesting2019/files/3535971/PRUEBAS.AUTOMATIZADAS.EN.ANGULAR.pdf)

**Comment by Basdf** [comment]
@DiegOliveros @natienamorado @veluaru @joh95 
- Posee descripción.
- Está asociada a un Milestone.
- Tiene un label.
- Está asociada a un proyecto.
- No tiene tareas asociadas.
- Tiene personas encargadas.
- Cuenta con documentación.

**Comment by alejovillegas7** [comment]
- [x] Introducción pruebas automatizadas en angular

- [x] definir pasos de instalacion y configuracion

- [x] desarrollar un pequeño ejemplo en la guia

**Comment by Basdf** [comment]
@DiegOliveros @natienamorado @veluaru @joh95
issue completo, lo pueden cerrar
