### ISSUE TITLE
Establecer herramientas para los tipos de pruebas

### ISSUE THREAD

**Issue by jazz1228** [calidadudea/CalidadTesting2019#2]
Se requiere establecer que tipos de pruebas  durante el proyecto: Para los diferentes tipos de prueba se debe validar que estas se lleven a cabo de la manera mas exitosa

**Comment by alejovillegas7** [comment]
[Mejores herramientas para Java y Angular.pdf](https://github.com/calidadudea/CalidadTesting2019/files/3535460/Mejores.herramientas.para.Java.y.Angular.pdf)

**Comment by Basdf** [comment]
@DiegOliveros @natienamorado @veluaru @joh95 
- Posee descripción.
- Está asociada a un Milestone.
- Tiene un label.
- Está asociada a un proyecto.
- No tiene tareas asociadas.
- Tiene personas encargadas.
- Cuenta con documentación.

**Comment by alejovillegas7** [comment]
- [x] definir porque se debe de utilziar cada herramienta para hacer los distintos tipos de pruebas(front y back)

- [x] establecer la amnera de probar el codigo de back

- [x] estabelecer la manera de probar los componentes que componen el front

**Comment by Basdf** [comment]
@DiegOliveros @natienamorado @veluaru @joh95
issue completo, lo pueden cerrar
