### ISSUE TITLE
Desarrollo de Pruebas para Backend

### ISSUE THREAD

**Issue by joh95** [calidadudea/CalidadTesting2019#4]
Pruebas usando JUnit

**Comment by jazz1228** [comment]
[Ejemplo de test en Back.pdf](https://github.com/calidadudea/CalidadTesting2019/files/3535920/Ejemplo.de.test.en.Back.pdf)

**Comment by Basdf** [comment]
@DiegOliveros @natienamorado @veluaru @joh95 
- Descripción deficiente.
- Está asociada a un Milestone.
- Tiene un label.
- Está asociada a un proyecto.
- No tiene tareas asociadas.
- Tiene personas encargadas.
- Cuenta con documentación.

**Comment by alejovillegas7** [comment]
- [x] definir objetivos

- [x] definir ejemplo o la configuracion de una prueba

**Comment by Basdf** [comment]
@DiegOliveros @natienamorado @veluaru @joh95
issue completo, lo pueden cerrar
