### ISSUE TITLE
Ejemplo de desarrollo de Pruebas para Frontend

### ISSUE THREAD

**Issue by joh95** [calidadudea/CalidadTesting2019#5]

**Comment by jazz1228** [comment]
[Ejemplo Test Front-End.pdf](https://github.com/calidadudea/CalidadTesting2019/files/3535909/Ejemplo.Test.Front-End.pdf)

**Comment by Basdf** [comment]
@DiegOliveros @natienamorado @veluaru @joh95 
- No posee descripción.
- Está asociada a un Milestone.
- Tiene un label.
- Está asociada a un proyecto.
- No tiene tareas asociadas.
- Tiene personas encargadas.
- Cuenta con documentación.

**Comment by alejovillegas7** [comment]
- [ ]definir ejemplo o la configuracion de una prueba

**Comment by alejovillegas7** [comment]
- [x] definir ejemplo o la configuracion de una prueba

**Comment by Basdf** [comment]
@DiegOliveros @natienamorado @veluaru @joh95
issue completo, lo pueden cerrar
