### ISSUE TITLE
Seleccionar las herramientas para Testing en el Back

### ISSUE THREAD

**Issue by jazz1228** [calidadudea/CalidadTesting2019#6]
Se debe contemplar el elegir una herramienta que se adapte y sea de fácil e intuitivo uso para el Test en el lado del Back. El lenguaje de programación que se usara es Java entonces se debe delimitar buscar una opción adecuada para dicho lenguaje.

**Comment by jazz1228** [comment]
[Junit - JAVA.pdf](https://github.com/calidadudea/CalidadTesting2019/files/3535889/Junit.-.JAVA.pdf)

**Comment by Basdf** [comment]
@DiegOliveros @natienamorado @veluaru @joh95 
- Posee descripción.
- Está asociada a un Milestone.
- Tiene un label.
- Está asociada a un proyecto.
- No tiene tareas asociadas.
- Tiene personas encargadas.
- Cuenta con documentación.

**Comment by alejovillegas7** [comment]
Seleccionar las herramientas para Testing en el Back

- [x] Por qué utilizar JUnit

- [x] Buscar las ventajas de utilziar Junit

**Comment by Basdf** [comment]
@DiegOliveros @natienamorado @veluaru @joh95
issue completo, lo pueden cerrar
