### ISSUE TITLE
Seleccionar las herramientas para el Testing en el Front

### ISSUE THREAD

**Issue by jazz1228** [calidadudea/CalidadTesting2019#7]
Se debe contemplar el uso de un marco de trabajo o herramienta que se adapte de manera fácil e intuitiva al sistema en el lado del Front. El framework para el Front a usar sera Angular y por ende se debe delimitar la búsqueda a herramientas diseñadas para usarse en conjunto con Angular.

**Comment by jazz1228** [comment]
[Componente de prueba - Angular.pdf](https://github.com/calidadudea/CalidadTesting2019/files/3535899/Componente.de.prueba.-.Angular.pdf)

**Comment by Basdf** [comment]
@DiegOliveros @natienamorado @veluaru @joh95 
- Posee descripción.
- Está asociada a un Milestone.
- Tiene un label.
- Está asociada a un proyecto.
- No tiene tareas asociadas.
- Tiene personas encargadas.
- Cuenta con documentación.

**Comment by alejovillegas7** [comment]
- [x] definir objetivos

- [x] definir ejemplo o la configuracion de una prueba

**Comment by Basdf** [comment]
@DiegOliveros @natienamorado @veluaru @joh95
issue completo, lo pueden cerrar
