### ISSUE TITLE
Investigar sobre la automatización de pruebas

### ISSUE THREAD

**Issue by jazz1228** [calidadudea/CalidadTesting2019#8]
Se debe realizar una investigación sobre el tipo de automatización y herramientas de automatización que ofrece la industria y para la industria.

**Comment by jazz1228** [comment]
[Pardo_LACREST_2013.pdf](https://github.com/calidadudea/CalidadTesting2019/files/3535952/Pardo_LACREST_2013.pdf)

**Comment by jazz1228** [comment]
https://www.guru99.com/automation-testing.html

**Comment by Basdf** [comment]
@DiegOliveros @natienamorado @veluaru @joh95 
- Posee descripción.
- Está asociada a un Milestone.
- Tiene un label.
- Está asociada a un proyecto.
- No tiene tareas asociadas.
- Tiene personas encargadas.
- Cuenta con documentación.

**Comment by alejovillegas7** [comment]
- [x] encontrar fuentes confiables en donde se explique de manera concreta la automatizacion de pruebas

**Comment by Basdf** [comment]
@DiegOliveros @natienamorado @veluaru @joh95
issue completo, lo pueden cerrar
