### ISSUE TITLE
Ejemplo y / o Guía de automatización de pruebas en Back

### ISSUE THREAD

**Issue by jazz1228** [calidadudea/CalidadTesting2019#9]
Se debe mostrar un ejemplo o guía sencilla donde se muestre el uso de la herramienta elegida en back para la automatización de las pruebas

**Comment by jazz1228** [comment]
[PRUEBAS AUTOMATIZADAS EN JAVA.pdf](https://github.com/calidadudea/CalidadTesting2019/files/3535984/PRUEBAS.AUTOMATIZADAS.EN.JAVA.pdf)

**Comment by Basdf** [comment]
@DiegOliveros @natienamorado @veluaru @joh95 
- Posee descripción.
- Está asociada a un Milestone.
- Tiene un label.
- Está asociada a un proyecto.
- No tiene tareas asociadas.
- Tiene personas encargadas.
- Cuenta con documentación.

**Comment by alejovillegas7** [comment]
- [x] Introduccion pruebas automatizadas en Java

- [x] definir requerimientos 

- [x] pequeño ejemplo de implemetación

**Comment by Basdf** [comment]
@DiegOliveros @natienamorado @veluaru @joh95
issue completo, lo pueden cerrar
